import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/shared/navbar/LaptopNavbar";
import Footer from "@/shared/navbar/Footer/Footer";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Bangladesh Engineers Council",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
